version:  "1.0"

services:  
  mysql:
    image: mysql:8.0.29
    container_name: IOTmysql
    networks:
      - iotNetwork
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: "IOTDB"
      MYSQL_USER: "iot"
      MYSQL_PASSWORD: "iot123"
    ports:
      - "3306:3306"
    volumes:
      - IOTMysqlData:/var/lib/mysql
      - IOTMysqlConfig:/etc/mysql

  mongo:
    image: mongo:5
    container_name: IOTmongo
    networks:
      - iotNetwork
    volumes:
      - IOTMongo:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=IOTDB
      - MONGO_INITDB_ROOT_USERNAME=iot
      - MONGO_INITDB_ROOT_PASSWORD=iot123

  dataflight:
    depends_on:
      - mysql
      - mongo
    build: ./DataFlight
    command: npm start
    container_name: IOTnode
    networks:
      - iotNetwork
    ports:
      - "3030:3030"
    volumes:
      - ./DataFlight:/api

networks:
  iotNetwork:
    driver: bridge

volumes:
  IOTMysqlData:
  IOTMysqlConfig:
  IOTMongo: