version:  "3.8"

services:  
  mysqldb:
    image: mysql:8.0.31
    container_name: IOTmysql
    env_file: ./.env
    networks:
      - iotNetwork
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - IOT_mysqlData:/var/lib/mysql
      - IOT_mysqlConfig:/etc/mysql
    

  influxdb:
    image: influxdb:2.1
    container_name: IOTinflux
    env_file: ./.env
    networks:
      - iotNetwork
    ports:
      - '8086:8086'
    environment:
      INFLUX_USERNAME: ${INFLUX_USERNAME}
      INFLUX_PASSWORD: ${INFLUX_PASSWORD}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
    volumes:
      - IOT_influx:/var/lib/influxdb

  dataflight:
    depends_on:
      - mysqldb
      - influxdb
    container_name: IOTnode
    build: .
    command: npm start
    networks:
      - iotNetwork
    ports:
      - "3030:3030"
    volumes:
      - .:/api
    stdin_open: true
    tty: true

networks:
  iotNetwork:
    driver: bridge

volumes:
  IOT_mysqlData:
  IOT_mysqlConfig:
  IOT_influx: